### ISSUE TITLE
Error custom Fields GLPI 9.4.3 and genericobject 2.7.0

### ISSUE THREAD

**Issue by whipcester** [pluginsGLPI/genericobject#261]
Hello,

I'm on GLPI 9.4.3 and genericobject 2.7.0.

I can't add a new custom dropdown field.

I try two methods:

$GO_FIELDS['plugin_genericobject_videoprojecteurlampes_id']['name']       = "Lampes";
$GO_FIELDS['plugin_genericobject_videoprojecteurlampes_id']['field']      = 'lampes';
$GO_FIELDS['plugin_genericobject_videoprojecteurlampes_id']['input_type'] = 'dropdown';

With this syntax when i click on "Add new field" i have a message "Field added successfully" but nothing appear in the list.

When i try this syntax:

$GO_FIELDS['videoprojecteurlampes_id']['name']       = "Lampes";
$GO_FIELDS['videoprojecteurlampes_id']['field']      = 'lampes';
$GO_FIELDS['videoprojecteurlampes_id']['input_type'] = 'dropdown';

I have the same message "Field added successfully" and my field appear in the list with DB name "plugin_genericobject_videoprojecteurlampes_id"

In Debug mode this message appear:
"Undefined index: lampes_id in GLPI\plugins\genericobject\inc\field.class.php at line 296"

In main tab if i click on save i have the following error:

PHP Fatal error:  Uncaught Exception: Invalid search option in "PluginGenericobjectVideoprojecteur": missing "name" field(s). Array
(
    [id] => 125
    [table] => glpi_plugin_genericobject_videoprojecteurlampes
    [field] => name
    [name] => 
    [injectable] => 1
    [datatype] => dropdown
)
 in GLPI\inc\commondbtm.class.php:3609
Stack trace:
#0 GLPI\inc\search.class.php(6598): CommonDBTM->searchOptions()
#1 GLPI\inc\search.class.php(6405): Search::getOptions('PluginGenericob...', true)
#2 GLPI\plugins\genericobject\inc\field.class.php(450): Search::getCleanedOptions('PluginGenericob...')
#3 GLPI\plugins\genericobject\inc\field.class.php(425): PluginGenericobjectField::deleteDisplayPreferences('glpi_plugin_gen...', 'is_template')
#4 GLPI\plugins\genericobject\inc\type.class.php(856): PluginGenericobjectField::deleteField('glpi_plugin_gen...', 'is_template')
#5 GLPI\plugins\genericobject\inc in GLPI\inc\commondbtm.class.php on line 3609

Best regards

**Comment by stonebuzz** [comment]
Hi @whipcester 

check documentation here -> https://glpi-plugins.readthedocs.io/en/master/genericobject/index.html#add-a-simple-dropdown-field

```
The language variable must be defined in the language file (see explaination above).
```

Best regards

**Comment by whipcester** [comment]
Hi @stonebuzz ,
Thanks,
I use language variable but now my custom field don't appear in the add new field dropdown list:

In debug mode i have this error:
PHP Notice: Undefined index: genericobject in GLPI\files\_plugins\genericobject\fields\videoprojecteur.constant.php at line 09

My videoprojecteur.constant.php
global $GO_FIELDS, $LANG;

$GO_FIELDS['plugin_genericobject_videoprojecteurlampes_id']['name']       = $LANG['genericobject']['PluginGenericobjectVideoprojecteur'][1];
$GO_FIELDS['plugin_genericobject_videoprojecteurlampes_id']['field']      = 'lampes';
$GO_FIELDS['plugin_genericobject_videoprojecteurlampes_id']['input_type'] = 'dropdown';

My language file:
$LANG['genericobject']['PluginGenericobjectVideoprojecteur'][0]="videoprojecteur";
$LANG['genericobject']['PluginGenericobjectVideoprojecteur'][1]="Lampes";

Best Regards,
